export const DESKTOP_COMMANDS = {
  files: {
    list: 'files_list',
    open: 'files_open',
    openExternal: 'files_open_external',
    search: 'files_search',
    getRecent: 'files_get_recent',
    getHome: 'files_get_home',
    selectFolder: 'files_select_folder',
    selectFile: 'files_select_file',
    selectAttachments: 'files_select_attachments',
    selectSaveFile: 'files_select_save_file',
    stat: 'files_stat',
    rename: 'files_rename',
    delete: 'files_delete',
    showInFolder: 'files_show_in_folder',
    removeRecent: 'files_remove_recent',
    copyToClipboard: 'files_copy_to_clipboard',
    historyList: 'files_history_list',
    historyRestore: 'files_history_restore',
  },
  documents: {
    readFile: 'documents_read_file',
    prepareWord: 'documents_prepare_word',
    preparePresentation: 'documents_prepare_presentation',
    prepareSpreadsheet: 'documents_prepare_spreadsheet',
    saveBinary: 'documents_save_binary',
    editPresentation: 'documents_edit_presentation',
    saveText: 'documents_save_text',
    listFonts: 'documents_list_fonts',
    copyImageToClipboard: 'documents_write_png_clipboard',
    setCurrentFile: 'documents_set_current_file',
  },
  agents: {
    list: 'agents_list',
    save: 'agents_save',
    delete: 'agents_delete',
    conversationsList: 'agents_conversations_list',
    conversationsGet: 'agents_conversations_get',
    conversationsSave: 'agents_conversations_save',
    conversationsDelete: 'agents_conversations_delete',
    conversationsImportCodex: 'agents_conversations_import_codex',
    chat: 'agents_chat',
    runTask: 'agents_run_task',
    cancel: 'agents_cancel',
    sendDocumentResult: 'agents_document_result',
    sendDocumentEvent: 'agents_document_event',
  },
  providers: {
    list: 'providers_list',
    get: 'providers_get',
    detectOllama: 'providers_detect_ollama',
    setBaseURL: 'providers_set_base_url',
    authGetAll: 'providers_auth_status',
    authSet: 'providers_auth_set',
    authRemove: 'providers_auth_remove',
    customList: 'providers_custom_list',
    customSave: 'providers_custom_save',
    customTestConnection: 'providers_custom_test',
    customDelete: 'providers_custom_delete',
  },
  process: {
    probeDependencies: 'process_probe_dependencies',
    runCode: 'process_run_code',
    debugStart: 'process_debug_start',
    debugStop: 'process_debug_stop',
    debugCommand: 'process_debug_command',
    debugEvaluate: 'process_debug_evaluate',
    terminalExec: 'process_terminal_exec',
    terminalKill: 'process_terminal_kill',
  },
  app: {
    setLanguage: 'app_i18n_set_language',
    setTheme: 'app_theme_set',
    performMenuAction: 'app_menu_perform',
    minimize: 'app_window_minimize',
    maximize: 'app_window_toggle_maximize',
    newWindow: 'app_window_new',
    toggleFullscreen: 'app_window_toggle_fullscreen',
    close: 'app_window_close',
    quit: 'app_quit',
    checkForUpdate: 'app_update_check',
    installUpdate: 'app_update_install',
    markStartupHealthy: 'app_startup_healthy',
    takeStartupFiles: 'app_take_startup_files',
  },
} as const
